medmenwork/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('medmenwork_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)






if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medmenwork_app/models.py
from django.db import models

# Create your models here.
from django.utils import timezone

class Banner(models.Model):
    BANNER_TYPES = (
        ('home', 'Home'),
        ('about', 'About'),
        ('services', 'Services'),
        ('contact', 'Contact'),
        # Add more types as needed
    )
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='media/banners/', default='media/banners/default.jpg')
    banner_type = models.CharField(max_length=50, choices=BANNER_TYPES)
    
    def __str__(self):
        return f"{self.title}"


class Client(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='clients/')
    contact = models.CharField(max_length=20, blank=True, null=True)
    link = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.name
    
class Service(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()

class about(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()

class SliderImage(models.Model):
    image = models.ImageField(upload_to='slider_images/')
    alt_text = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.alt_text if self.alt_text else f"Slider Image {self.id}"

PRODUCT_CHOICES = [
    ('leather_ladies_hand_bag', 'Leather Ladies Hand Bag'),
    ('leather_hand_bags', 'Leather Hand Bags'),
    ('leather_laptop_bags', 'Leather Laptop Bags'),
    ('leather_backpack', 'Leather Backpack'),
    ('leather_wallet', 'Leather Wallet'),
    ('leather_accessories', 'Leather Accessories'),
    ('leather_home_decor', 'Leather Home Decor'),    
    ('leather_jackets', 'Leather Jackets'),
    ('leather_watch_straps', 'Leather Watch Straps'),
]

class Contact(models.Model):
    full_name = models.CharField(max_length=100)
    company = models.CharField(max_length=100, blank=True, null=True)
    phone_number = models.CharField(max_length=40, blank=True, null=True)
    email = models.EmailField()
    website = models.URLField(blank=True, null=True)
    product_interest = models.CharField(max_length=100, choices=PRODUCT_CHOICES)
    enquiry = models.TextField()

    # def __str__(self):
    #     return f"{self.first_name} {self.last_name} - {self.product_interest}"



class LeatherProduct(models.Model):

    
    category = models.CharField(max_length=200, choices=PRODUCT_CHOICES)
    image = models.ImageField(upload_to='products/')
    description = models.TextField(blank=True, null=True)
    
    def __str__(self):
        return self.get_category_display()




class Settings(models.Model):
    phone = models.CharField(max_length=20, blank=True, null=True)
    telephone = models.CharField(max_length=20, blank=True, null=True)
    whatsapp_number = models.CharField(max_length=20, blank=True, null=True)
    email_id = models.EmailField(max_length=254, blank=True, null=True)
    address1 = models.CharField(max_length=255, blank=True, null=True)
    address2 = models.CharField(max_length=255, blank=True, null=True)
    fb_link = models.URLField(max_length=200, blank=True, null=True)
    ig_link = models.URLField(max_length=200, blank=True, null=True)
    linkedin = models.URLField(max_length=200, blank=True, null=True)
    twitter = models.URLField(max_length=200, blank=True, null=True)
    youtube = models.URLField(max_length=200, blank=True, null=True)
    copyright = models.URLField(max_length=200, blank=True, null=True)

    def __str__(self):
        return f"Settings ({self.id})"


class TeamMember(models.Model):
    name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    image = models.ImageField(upload_to='team_images/')

    def __str__(self):
        return self.name


class Activity(models.Model):
    image = models.ImageField(upload_to='activities/')
    date = models.DateField()
    description = models.CharField(max_length=255)

    def __str__(self):
        return self.description[:50]

templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Madmen work</title>
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'assets/main.css/mobile.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" />
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
</head>

<body>
    
    <nav class="navbar navbar-expand-xl  navbar-dark main_header" aria-label="Offcanvas navbar large">
        <div class="container-lg">
            <a class="navbar-brand" href="{% url 'home' %}">
                <div class="the_logo"><img src="{% static 'assets/Image/main_logo.png' %}" alt="" class="w-100"></div>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar2"
                aria-controls="offcanvasNavbar2">
                <span class="navbar-toggler-icon"><i class="fa-solid fa-bars"></i></span>
            </button>
            <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar2"
                aria-labelledby="offcanvasNavbar2Label">
                <div class="offcanvas-header">
                    <!-- <h5 class="offcanvas-title" id="offcanvasNavbar2Label"></h5> -->
                    <a href=""><img src="{% static 'assets/Image/main_logo.png' %}" alt="" class="w-100"></a>
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="manubar_main">
                    <ul class="navbar-nav manu_bg flex-grow-1 pe-3 mb-0">
                        <li class="nav-item"><a href=" {% url 'home' %}" class="nav-link">Home</a></li>
                        <li class="nav-item"><a href="{% url 'about_us' %}" class="nav-link">About Us</a></li>
                        <li class="nav-item"><a href="" class="nav-link">Product Catalogue</a></li>
                        <li class="nav-item"><a href="{% url 'services' %}" class="nav-link">Our Services</a></li>
                        {% comment %} <li class="nav-item"><a href="" class="nav-link">Sustainability</a></li> {% endcomment %}
                        <li class="nav-item menuBtn"><a href="{% url 'contact' %}" class="nav-link nav_btn">Contact Us</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>

    {% block content %}



    {% endblock content %}

     <!-- Footer Section Start -->
     <footer class="main_footer mt-3">
        <div class="container-lg">
            <div class="row">
                <div class="col-lg-4 col-xl-4 col-lg-5 col-md-6">
                    <a class="navbar-brand" href="{% url 'home' %}">
                        <div class="footer_image">
                            <img src="{% static 'assets/Image/footer_logo.png' %}" alt="">
                        </div>
                    </a>
                    <div class="footer_text">
                        <p>"Madmenwork specializes in crafting timeless leather products like bags, jackets, and more. Each piece blends elegance with durability, defining sophistication." </p>
                    </div>
                </div>
                <div class="col-lg-4 col-xl-3 col-md-6">
                    <div class="footer_content">
                        <h5>Contact Us:</h5>
                        <div class="link_footer d-flex">
                            <p><a href="" class=" d-flex align-items-center"> <i class="fa-regular fa-envelope"></i>
                                    {{settings.email_id}}</a></p>
                        </div>
                        <div class="link_footer d-flex">
                            <p><i class="fa-solid fa-phone"></i></p>
                            <p><a href="">{{settings.phone}}</a></p>
                        </div>
                        <h5>Location:</h5>
                        <div class="link_footer d-flex">
                            <p> <i class="fa-solid fa-location-dot"></i></p>
                            <p><a href="">{{settings.address1}}</a></p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-xl-2 col-md-6">
                    <div class="footer_content">
                        <h5>Quick Link’s:</h5>
                        <p><a href="{% url 'home' %}">Home</a></p>
                        <p><a href="{% url 'about_us' %}">About Us</a></p>
                        <p><a href="#">Product Catalogue</a></p>
                        <p><a href="{% url 'services' %}">Our Services</a></p>
                    </div>
                </div>
                <div class="col-lg-6 col-xl-3 col-md-6">
                    <div class="footer_last_bg">
                        <div class="heading_bg">
                            <h5>Follow Us:</h5>
                        </div>
                        <div class="social_icon">
                            <a href="{{settings.fb_link}}"><i class="fa-brands fa-facebook"></i></a>
                            <a href="{{settings.twitter}}"><i class="fa-brands fa-twitter"></i></a>
                            <a href="{{settings.ig_link}}"><i class="fa-brands fa-instagram"></i></a>
                            <a href="{{settings.youtube}}"><i class="fa-brands fa-youtube"></i></a>
                        </div>
                    </div>
                    <div class="subscribe_bg mt-4">
                        <h5>Subscribe:</h5>
                        <input type="email" placeholder="Email Address">
                        <div class="sent_btn">
                            <a href=""><i class="fa-solid fa-paper-plane"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="team_bg d-flex justify-content-end align-items-center gap-5 mt-4">
                        <div class="left_bg">
                            <a href="">Terms and condition</a>
                        </div>
                        <div class="right_bg">
                            <a href="">Privacy policy</a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->








    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'assets/java script/script.js' %}"></script>
    
    

    <!-- JavaScript to handle form submission and show SweetAlert -->
    
    
</body>

</html>

templates/contact.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <!-- Main Top navbar End -->

    <!-- Banner-Section-Start -->
    <section class="main_banner">
        <div class="banner_body">
            <div class="container-lg">
                <div class="row justify-content-between align-items-center pb-lg-5 pb-4">
                    <div class="col-lg-6">
                        <div class="banner_text">
                            {% for item in banners %}
                                <h5>{{ item.title }}</h5>
                                <p>{{ item.description }}</p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="clients_details float-lg-end">
                            <div class="text_bg">
                                <p>Our Clients</p>
                                {% for client in clients %}
                                <div class="clients_link d-flex align-items-center gap-2 pb-3">
                                    <div class="d-flex clinets_box">
                                        <div class="clients_image">
                                            <a href="{{ client.link }}"><img src="{{ client.image.url }}" alt="{{ client.name }}"></a>
                                        </div>                                              
                                    </div>

                                    <div class="clients_meet">
                                        <a href="{{ client.link }}">See more+</a>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                            <div class="clients_link d-flex align-items-center gap-2 mt-2">
                                <div class="clients_image">
                                    <a href=""><img src="{% static 'assets/Image/clients2.png' %}" alt=""></a>
                                </div>
                                <div class="clients_meet">
                                    <p class="mb-0">Contact</p>
                                    <a href="">(+91) 7309902183</a>
                                </div>
                            </div>
                            <div class="decover_btn mt-4">
                                <a href="">Discover more</a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="about_image">
                {% for item in banners %}
                <img src="{{ item.image.url }}" alt="{{ item.title }}" class="w-100">
                {% endfor %}
            </div>
        </div>
    </section>
    <!-- Banner-Section-End -->

    <!-- Sending Massage Section Start -->
    <section class="send_massage">
        <div class="container-lg">
            <div class="row">
                <div class="col-lg-8">
                    <form action="" method="post" class="form_box" id="contact-form" novalidate>
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-4 col-md-6 mb-3">
                                <div class="input_field">
                                    {{ form.full_name.label_tag }}
                                    {{ form.full_name }}
                                    <small class="text-danger">{{ form.full_name.errors }}</small>
                                </div>
                            </div>
        
                            <div class="col-lg-4 col-md-6 mb-3">
                                <div class="input_field">
                                    {{ form.company.label_tag }}
                                    {{ form.company }}
                                    <small class="text-danger">{{ form.company.errors }}</small>
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-6 mb-3">
                                <div class="input_field">
                                    {{ form.phone_number.label_tag }}
                                    {{ form.phone_number }}
                                    <small class="text-danger">{{ form.phone_number.errors }}</small>
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-6 mb-3">
                                <div class="input_field">
                                    {{ form.email.label_tag }}
                                    {{ form.email }}
                                    <small class="text-danger">{{ form.email.errors }}</small>
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-6 mb-3">
                                <div class="input_field">
                                    {{ form.website.label_tag }}
                                    {{ form.website }}
                                    <small class="text-danger">{{ form.website.errors }}</small>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="bg">
                                    <p>{{ form.product_interest.label_tag }}</p>
                                </div>
                            </div>
                        <div class="col-12">
                            <div class="radio_bg">
                                {% for radio in form.product_interest %}
                                    <div class="radio_group">
                                        {{ radio.tag }}
                                        {{ radio.choice_label }}
                                    </div>
                                {% endfor %}
                                <small class="text-danger">{{ form.product_interest.errors }}</small>
                            </div>
                        </div>
                            <div class="col-12 mt-3">
                                <div class="text_write">
                                    {{ form.enquiry.label_tag }}<span>*</span>
                                    {{ form.enquiry }}
                                    <small class="text-danger">{{ form.enquiry.errors }}</small>
                                </div>
                            </div>
                            <div class="col-3">
                                <div class="smt_btn mt-4">
                                   
                                    <button type="submit" class="btn btn-primary" onclick="submitForm()">Submit</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-lg-4">
                    <div class="massage_body mb-3">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="content_fl">
                                    <div class="cyrcle_area">
                                        <a href=""><i class="fa-solid fa-phone-volume"></i></a>
                                    </div>
                                    <div class="num_contect">
                                        <p><a href="">Phone Number</a></p>
                                        <h5><a href="">+91 8303992628</a></h5>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="massage_body mb-3">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="content_fl">
                                    <div class="cyrcle_area">
                                        <a href=""><i class="fa-solid fa-envelope"></i></a>
                                    </div>
                                    <div class="num_contect">
                                        <p><a href="">Email</a></p>
                                        <h5><a href="">Madmenwork@gmail.com</a></h5>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="massage_body">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="content_fl">
                                    <div class="cyrcle_area">
                                        <a href=""><i class="fa-solid fa-location-dot"></i></a>
                                    </div>
                                    <div class="num_contect">
                                        <p><a href="">Location</a></p>
                                        <h5><a href="">Suite 972 Hyon Club, WV 62449</a></h5>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        </div>

        </div>
        </div>
        </div>
        </div>
    </section>
    <!-- Sending Massage Section End -->

    <!-- Find Map's Section Start -->
    <section class="map_area">
        <div class="container-lg">
            <div class="row">
                <div class="col-12">
                    <div class="map_text">
                        <h5><label for="" class="color_text">Follow Us</label> On Map</h5>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Find Map's Section End -->


     

    <!-- Compliance Section Start -->
    <section class="compliance_main">
        <div class="container-lg">
            <div class="row justify-content-center align-items-center">
                <div class="col-lg-8 col-12">
                    <div class="story_contant">
                        <h5><label for="" class="color_text">Compliance</label></h5>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has
                            been the industry's standard dummy text ever since the 1500s</p>
                    </div>
                </div>
            </div>

            <div class="row justify-content-center align-items-center">
                <div class="col-lg-2 col-6">
                    <div class="compliace_image">
                        <img src="{% static 'assets/Image/complinces1.png' %}" alt="">
                    </div>
                </div>
                <div class="col-lg-2 col-6">
                    <div class="compliace_image">
                        <img src="{% static 'assets/Image/complinces2.png' %}" alt="">
                    </div>
                </div>
                <div class="col-lg-2 col-6">
                    <div class="compliace_image">
                        <img src="{% static 'assets/Image/complinces1.png' %}" alt="">
                    </div>
                </div>
                <div class="col-lg-2 col-6">
                    <div class="compliace_image">
                        <img src="{% static 'assets/Image/complinces3.png' %}" alt="">
                    </div>
                </div>
            </div>

        </div>
        </div>
    </section>
    <!-- Compliance Section End -->
    

        <script>
    
        // Function to show SweetAlert on form submission success or failure
        function showAlert(message, alertType) {
            swal({
            title: message,
            icon: alertType,
            button: "OK",
            });
        }
        </script>
    
    
    
        <script>
            // Function to handle form submission
            function submitForm() {
            document.getElementById('contactForm').submit();
            }
        
            // Django form submission success or failure handling
            {% if messages %}
            {% for message in messages %}
                showAlert("{{ message }}", "{{ message.tags }}");
            {% endfor %}
            {% endif %}
        </script>

{% endblock content %} 

templates/contact_form.html
<!-- templates/home.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Us</title>
</head>
<body>
<section class="contact_us">
    <div class="container-lg">
        <div class="row justify-content-center align-items-center">
            <div class="col-lg-8 col-12">
                <div class="contact_text">
                    <h5>Contact</h5>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
                </div>
            </div>
        </div>
        <form method="post" action="">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-4 col-md-6 mb-3">
                    <div class="input_field">
                        <label for="id_first_name">First Name</label>
                        {{ form.first_name }}
                        {% if form.first_name.errors %}
                            <div class="error">{{ form.first_name.errors }}</div>
                        {% endif %}
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-3">
                    <div class="input_field">
                        <label for="id_last_name">Last Name</label>
                        {{ form.last_name }}
                        {% if form.last_name.errors %}
                            <div class="error">{{ form.last_name.errors }}</div>
                        {% endif %}
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-3">
                    <div class="input_field">
                        <label for="id_company">Company</label>
                        {{ form.company }}
                        {% if form.company.errors %}
                            <div class="error">{{ form.company.errors }}</div>
                        {% endif %}
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-3">
                    <div class="input_field">
                        <label for="id_phone_number">Phone Number</label>
                        {{ form.phone_number }}
                        {% if form.phone_number.errors %}
                            <div class="error">{{ form.phone_number.errors }}</div>
                        {% endif %}
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-3">
                    <div class="input_field">
                        <label for="id_email">Your Email</label>
                        {{ form.email }}
                        {% if form.email.errors %}
                            <div class="error">{{ form.email.errors }}</div>
                        {% endif %}
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-3">
                    <div class="input_field">
                        <label for="id_website">Your Website</label>
                        {{ form.website }}
                        {% if form.website.errors %}
                            <div class="error">{{ form.website.errors }}</div>
                        {% endif %}
                    </div>
                </div>
                <div class="col-12">
                    <div class="bg">
                        <p>Which Product/Service Are You Interested In*</p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="radio_bg">
                        {% for choice in form.product_interest.field.choices %}
                            <div class="radio_group">
                                <input type="radio" name="product_interest" id="product_interest_{{ forloop.counter }}" value="{{ choice.0 }}" class="large_radio" {% if form.product_interest.value == choice.0 %}checked{% endif %}>
                                <label for="product_interest_{{ forloop.counter }}">{{ choice.1 }}</label>
                            </div>
                        {% endfor %}
                        {% if form.product_interest.errors %}
                            <div class="error">{{ form.product_interest.errors }}</div>
                        {% endif %}
                    </div>
                </div>
                <div class="col-12 mt-3">
                    <div class="text_write">
                        <label for="id_enquiry">Enquiry<span>*</span></label>
                        {{ form.enquiry }}
                        {% if form.enquiry.errors %}
                            <div class="error">{{ form.enquiry.errors }}</div>
                        {% endif %}
                    </div>
                </div>
                <div class="col-3">
                    <div class="smt_btn mt-4">
                        <button type="submit">Submit</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>
</body>
</html>